### ISSUE TITLE
Can't drop tables that aren't there

### ISSUE THREAD

**Issue by memo330179** [BCStudentSoftwareDevTeam/Ullman_Galleries#17]
When initially running the script when loading dummy data. This error comes up because we are trying to drop tables that don't exist.
```python
Traceback (most recent call last):
  File "scripts/ConfigureApp.py", line 133, in <module>
    create.main()
  File "scripts/ConfigureApp.py", line 127, in main
    self.create_mysql_database()
  File "scripts/ConfigureApp.py", line 86, in create_mysql_database
    self.add_dummy_data()
  File "scripts/ConfigureApp.py", line 118, in add_dummy_data
    dummy_data()
  File "/home/ubuntu/workspace/scripts/dummy_data.py", line 25, in dummy_data
    drop_tables()
  File "/home/ubuntu/workspace/scripts/dummy_data.py", line 17, in drop_tables
    model.drop_table()
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 5088, in drop_table
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 3954, in drop_table
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 3837, in execute_sql
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 3656, in __exit__
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 135, in reraise
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/peewee-2.10.2-py3.4.egg/peewee.py", line 3830, in execute_sql
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/ubuntu/workspace/venv/lib/python3.4/site-packages/mysqlclient-1.3.12-py3.4-linux-x86_64.egg/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
peewee.OperationalError: (1051, "Unknown table 'images'")
```

**Comment by Jessonsotoventura** [comment]
#24
